#!/bin/bash

for dir in `find /home/user -regextype posix-extended -regex ".*/Backup-[0-9]{4}-[0-9]{2}-[0-9]{2}"`
do
	dateOfDirStr=`echo $dir | awk -F'-' '{print $2"-"$3"-"$4}'`
        date=`date -d $dateOfDirStr '+%s'`
	if [[ -z $maxDate || $date -gt $maxDate ]]
	then
        	nameOfMax=$dir
		maxDate=$date
	fi
done

echo $nameOfMax
if [[ -z $nameOfMax ]]
then
	echo "Backup doesn't exist"
fi

cd $nameOfMax
echo $nameOfMax

mkdir -p "/home/user/restore"
for file in `find * `
do
	#pattern="[[:digit:]]"
	pattern="-[0-9]{4}-[0-9]{2}-[0-9]{2}$"
	if ! [[ $file =~ $pattern ]]
	then
		if [[ -d $file ]]; then continue; fi
#		echo $file
		path=`echo $file | awk 'BEGIN{FS="/"; OFS="/"} {NF--; print}'`

		mkdir -p /home/user/restore/$path

		cp $file /home/user/restore"/"$file
	fi
done
